// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmDsUBQPeWArQFBhoEC4s1kpR8XCsw0I',
    appId: '1:462934459270:web:bed2af2a734a49c707e207',
    messagingSenderId: '462934459270',
    projectId: 'jewellery-app-24c74',
    authDomain: 'jewellery-app-24c74.firebaseapp.com',
    storageBucket: 'jewellery-app-24c74.firebasestorage.app',
    measurementId: 'G-Q03KD3T4C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlVfnCMiQfMvsvREi5TzrfRh_-1rCPg4',
    appId: '1:462934459270:android:f5c5e312c2ed1eaa07e207',
    messagingSenderId: '462934459270',
    projectId: 'jewellery-app-24c74',
    storageBucket: 'jewellery-app-24c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjuhUbswthEWnblg74OBix_B4nvYV7Mk',
    appId: '1:462934459270:ios:2bae10551d757fed07e207',
    messagingSenderId: '462934459270',
    projectId: 'jewellery-app-24c74',
    storageBucket: 'jewellery-app-24c74.firebasestorage.app',
    iosBundleId: 'com.example.jewelleryapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYjuhUbswthEWnblg74OBix_B4nvYV7Mk',
    appId: '1:462934459270:ios:2bae10551d757fed07e207',
    messagingSenderId: '462934459270',
    projectId: 'jewellery-app-24c74',
    storageBucket: 'jewellery-app-24c74.firebasestorage.app',
    iosBundleId: 'com.example.jewelleryapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBmDsUBQPeWArQFBhoEC4s1kpR8XCsw0I',
    appId: '1:462934459270:web:418035e291aec13707e207',
    messagingSenderId: '462934459270',
    projectId: 'jewellery-app-24c74',
    authDomain: 'jewellery-app-24c74.firebaseapp.com',
    storageBucket: 'jewellery-app-24c74.firebasestorage.app',
    measurementId: 'G-C9D4NNZYHW',
  );
}
